name: "Compliance"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

permissions:
  pull-requests: write

jobs:
  compliance:
    uses: TMCB-SPACE/.github/.github/workflows/compliance.yml@main
