name: "Development"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  development:
    uses: TMCB-SPACE/.github/.github/workflows/development.yml@main
